### PR TITLE
Fix: (temporary until redesign) the recruitment page

### LINKED ISSUE #757: Fix correct available roles not showing up

### PR DESCRIPTION
**Pull request by Nimejandro**
## Describe your changes

Fixes: #

## Checklist before requesting review

- [x] Feature/fix PRs should add one atomic (as small as possible) feature or fix.
- [x] All code in your PR needs to have been formatted.
- [x] The merge commit title should be prefixed with the type of the PR and a colon and a space, that is "feat", "fix", "doc", "chore", or "refactor", followed by a ": ".
- [x] The merge commit body should reference at least one issue.
- [x] The code compiles and all the tests pass.

### CODE REVIEW

File: src/components/Recruitment/index.js [hunk 1]
```diff
@@ -5,20 +5,28 @@ import './index.scss'
...
 import { StickyContainer, Sticky } from 'react-sticky'
 //Come up with a solution using position: sticky in css instead
+
+/* Fixed by Nima 27-03-2023. Please read axios manual... Previously it was set to setGroups(result[0].groups) so it would only get the first one... */
 const Recruitment = () => {
     const navbarOffset = 60
     const [groups, setGroups] = useState()
     const [recruitmentLink, setRecruitmentLink] = useState('')
-
+    let mergedGroupsObject = {}
```
Comment (hampfh) [inline src/components/Recruitment/index.js]: Why is this variable defined outside of the useEffect?

File: src/components/Recruitment/index.js [hunk 2]
```diff
@@ -5,20 +5,28 @@ import './index.scss'
...
     useEffect(() => {
         axios.get('https://ais.armada.nu/api/recruitment').then(res => {
             let result = res.data
```
Comment (hampfh) [inline src/components/Recruitment/index.js]: I know this is not your code but it would be nice to properly make this a const since it isn't modified anywhere in the function

File: src/components/Recruitment/index.js [hunk 3]
```diff
@@ -5,20 +5,28 @@ import './index.scss'
...
-                setGroups(result[0].groups)
-                setRecruitmentLink(result[0].link)
-            }
+
+            result.forEach(item => {
+                const gr = item.groups
+                if (result.length > 0) {
+                    mergedGroupsObject = { ...mergedGroupsObject, ...gr }
+                    //setGroups(result[0].groups)
+                    setRecruitmentLink(result[0].link) //this line is still fine since the link is same for all of them
```
Comment (hampfh) [inline src/components/Recruitment/index.js]: Right now this value is repeatedly being set in every iteration in the loop which isn't optimal, I would suggest check if the value is set before setting it to prevent unnecessary updates:
```js
if (recruitmentLink.length <= 0) setRecruitmentLink(result[0].link)
```

**Review by hampfh — COMMENTED** [review]
Nice work @Nimejandro, thanks for fixing this on such a short notice! Great job 👍 

I left a few nitpicks that would be great if you could address before we merge

File: src/components/Recruitment/index.js (hunk 2 above)
Comment (Nimejandro) [reply src/components/Recruitment/index.js]: It's being changed every loop

File: src/components/Recruitment/index.js (hunk 3 above)
Comment (Nimejandro) [reply src/components/Recruitment/index.js]: True. That was there before

File: src/components/Recruitment/index.js (hunk 2 above)
Comment (hampfh) [reply src/components/Recruitment/index.js]: [Non-blocking] The variable is never mutated, so even though it is created every loop it can still be a "const" in js since we're never doing `result = ...`

**Review by hampfh — APPROVED** [review]
Great work, thanks @Nimejandro!

File: src/components/Recruitment/index.js (hunk 2 above)
Comment (Nimejandro) [reply src/components/Recruitment/index.js]: Jaha. Ok i thought you meant the other variable now i understand
